[package]
name = "wolfssl-sys"
version = "0.1.3"
edition = "2021"
authors = ["pete.m@expressvpn.com"]
license = "GPL-2.0"
readme = "README.md"
description = "System bindings for WolfSSL"
repository = "https://github.com/expressvpn/wolfssl-sys"
keywords = ["wolfssl", "vpn", "expressvpn", "lightway"]
links = "wolfssl"

[build-dependencies]
bindgen = "0.59.2"
autotools = "0.2"
