name: CI
on:
  push:
    branches: [main]
  pull_request: null # target every PR
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.15
      - uses: actions/checkout@v3
      - name: Run Tests
        run: earthly --ci +run-tests
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.15
      - uses: actions/checkout@v3
      - name: Build crate
        run: earthly --ci +build-release
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.15
      - uses: actions/checkout@v3
      - name: Lint crate
        run: earthly --ci +lint
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check bans licenses sources
