name: CI
on:
  push:
    branches: [main]
  pull_request: null # target every PR
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: earthly_visit_temp
    env:
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.17
      - uses: actions/checkout@v3
      - name: Run +ci on earthly satellites
        run: earthly --org expressvpn --satellite wolfssl --ci +ci